name: Ludic Linux
description: Ludic Linux 
url: http://ludiclinux.com
baseurl: ""
imagedir: "/images/"
defaults:
    -   
        scope:
            path: ""
            type: "posts"
        values:
            comments: false
            layout: post
    -   
        scope:
            path: ""
            type: "drafts"
        values:
            comments: false
            layout: post
gems: [jekyll-paginate]
paginate: 10 
paginate_path: "/:num"
links:
    Home:
        url: /
        image: /images/emblem.png
    Readme:
        url: https://github.com/LudicLinux/LudicLinux.github.io/blob/master/README.md
        image: /images/about_icon.png
    Contact:
        url: mailto:uo.is.ou+ludic@gmail.com 
        image: /images/email_icon.png
    Atom Feed:
        url: /atom.xml 
        image: /images/atom_icon.png
    GitHub:
        url: https://github.com/LudicLinux/LudicLinux.github.io 
        image: /images/githube_icon.png
authors:
    uoou:
        name: Piento 
        link: http://steamcommunity.com/id/uoou/ 
        email: uo.is.ou+ludic@gmail.com
    qN:
        name: "qptain Nemo"
        link: http://lazyandsleepy.org
        email: qptainnemo@gmail.com
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/
