name: Rounded Globe
description: Rounded Globe 
url: http://roundedglobe.github.io/blog
twitter_username: roundedglobe
baseurl: ""
imagedir: "/images/"
defaults:
    -   
        scope:
            path: ""
            type: "posts"
        values:
            comments: true
            layout: post
            image: books_header.jpg
    -   
        scope:
            path: ""
            type: "drafts"
        values:
            comments: false
            layout: post
gems: [jekyll-paginate]
paginate: 10 
paginate_path: "/:num"
links:
    Home:
        url: /
        image: emblem.png
    Twitter:
        url: https://twitter.com/roundedglobe
        image: twitter_icon.png
    Facebook:
        url: https://www.facebook.com/roundedglobe
        image: facebook_icon.png
    Atom Feed:
        url: /atom.xml 
        image: atom_icon.png
    Rounded Globe:
        url: http://roundedglobe.com/
        image: rg_icon.png
authors:
    rg:
        name: Rounded Globe 
        email: roundedglobe@gmail.com
        link: http://roundedglobe.com/
    bhammond:
	    name: Bryn Hammond
		bio: "Bryn Hammond was born in Britain but grew up and now lives in Australia. Her imagination was early captured by **Anna Comnena’s Turks** and **Gibbon’s barbarians**. Ten years ago she went part-time in her lowly job in Sydney, in order to work on __Amgalant__. Last year she found Sydney life unsustainable and downsized to the town of Ulladulla, where the rent is cheap and the seaside walks keep her creative. Hammond's acclaimed __Amgalant__ series, which has brought to life the stirring events of Mongol history on the twelfth-century Steppe, can be purchased (in print or electronic form) from her [website](http://amgalant.com/)."
		links:
		    Website: http://amgalant.com/
			Twitter: https://twitter.com/Jakujin
	jschmitt:
        name: Jason Schmitt
        bio: "Professor/writer/blogger/speaker. I write for Huffington Post and Slate about new technology, startups, open access and higher education."
        links:
            Website: http://jasonschmitt.com/ 
            Facebook: http://blah.com/
            Google+: http://something.org/
            Twitter: https://twitter.com/jason_schmitt
            Email: mailto:blah@blah.com
    gstroumsa:
        name: Guy Stroumsa
        bio: "Guy G. Stroumsa is Martin Buber Professor Emeritus of Comparative Religion, The Hebrew University of Jerusalem and Professor Emeritus of the Study of the Abrahamic Religions, and Emeritus Fellow of Lady Margaret Hall, University of Oxford. He is a member of the Israel Academy of Sciences and Humanities and holds an honorary doctorate from the University of Zurich. He is a laureate of the Humboldt Research Award, and a Chevalier dans l’Ordre du Mérite.<br /><br />His recent publications include:<br /><br /><em><a href=\"http://www.press.uchicago.edu/ucp/books/book/chicago/E/bo5747718.html\">The End of Sacrifice: Religious Transformations of Late Antiquity</a></em> (Chicago, 2009; paperback 2012)<br /><em><a href=\"http://www.hup.harvard.edu/catalog.php?isbn=9780674048607\">A New Science: the Discovery of Religion in the Age of Reason</a></em> (Cambridge, Mass., 2010)<br /><em><a href=\"https://global.oup.com/academic/product/the-making-of-the-abrahamic-religions-in-late-antiquity-9780198738862?cc=il&lang=en\">The Making of the Abrahamic Religions in Late Antiquity</a></em> (Oxford, 2015)<br />He is the co-editor, with Adam Silverstein, of <em><a href=\"https://global.oup.com/academic/product/the-oxford-handbook-of-the-abrahamic-religions-9780199697762?cc=il&lang=en\">The Oxford Handbook of the Abrahamic Religions</a></em> (Oxford, 2015)."
        links:
            Academia.edu: https://huji.academia.edu/guystroumsa
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/
