name: Rounded Globe
description: Rounded Globe 
url: http://roundedglobe.github.io/blog/
baseurl: ""
imagedir: "/images/"
defaults:
    -   
        scope:
            path: ""
            type: "posts"
        values:
            comments: true
            layout: post
            image: books_header.jpg
    -   
        scope:
            path: ""
            type: "drafts"
        values:
            comments: false
            layout: post
gems: [jekyll-paginate]
paginate: 10 
paginate_path: "/:num"
links:
    Home:
        url: /
        image: emblem.png
    Twitter:
        url: https://twitter.com/roundedglobe
        image: twitter_icon.png
    Facebook:
        url: https://www.facebook.com/roundedglobe
        image: facebook_icon.png
    Atom Feed:
        url: /atom.xml 
        image: atom_icon.png
    Rounded Globe:
        url: http://roundedglobe.com/
        image: rg_icon.png
authors:
    rg:
        name: Rounded Globe 
        email: roundedglobe@gmail.com
        link: http://roundedglobe.com/
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/
