name: Rounded Globe
description: Rounded Globe 
url: http://roundedglobe.github.io/blog
twitter_username: roundedglobe
baseurl: ""
imagedir: "/images/"
defaults:
    -   
        scope:
            path: ""
            type: "posts"
        values:
            comments: true
            layout: post
            image: books_header.jpg
    -   
        scope:
            path: ""
            type: "drafts"
        values:
            comments: false
            layout: post
gems: [jekyll-paginate]
paginate: 10 
paginate_path: "/:num"
links:
    Home:
        url: /
        image: emblem.png
    Twitter:
        url: https://twitter.com/roundedglobe
        image: twitter_icon.png
    Facebook:
        url: https://www.facebook.com/roundedglobe
        image: facebook_icon.png
    Atom Feed:
        url: /atom.xml 
        image: atom_icon.png
    Rounded Globe:
        url: http://roundedglobe.com/
        image: rg_icon.png
authors:
    rg:
        name: Rounded Globe 
        email: roundedglobe@gmail.com
        link: http://roundedglobe.com/
    bhammond:
        name: Bryn Hammond
        bio: "Bryn Hammond was born in Britain but grew up and now lives in Australia. Her imagination was early captured by Anna Comnena’s Turks and Gibbon’s barbarians. Her acclaimed __Amgalant__ series of historical novels, which has brought to life the stirring events of Mongol history on the twelfth-century Steppe, can be purchased (in print or electronic form) from her website, [Amgalant](http://amgalant.com/)."
        links:
            Website: http://amgalant.com/
            Twitter: https://twitter.com/Jakujin
    jschmitt:
        name: Jason Schmitt
        bio: "Professor/writer/blogger/speaker. He writes for Huffington Post and Slate about new technology, startups, open access and higher education."
        links:
            Website: http://jasonschmitt.com/ 
            Twitter: https://twitter.com/jason_schmitt
    sjcook:
        name: Simon J. Cook
        bio: "Simon J. Cook is an intellectual historian and independent scholar. His award-winning monograph on the political economist Alfred Marshall was published by Cambridge University Press in 2009 and costs $109.99. His recent essay on _J.R.R. Tolkien’s Lost English Mythology_ is [available for free on Rounded Globe](http://roundedglobe.com/book/54f6fe79648a590459746be1/J.R.R.%20Tolkien's%20Lost%20English%20Mythology)."
        links:
            Website: http://yemachine.com/
    gstroumsa:
        name: Guy Stroumsa
        bio: "Guy G. Stroumsa is Martin Buber Professor Emeritus of Comparative Religion, The Hebrew University of Jerusalem and Professor Emeritus of the Study of the Abrahamic Religions, and Emeritus Fellow of Lady Margaret Hall, University of Oxford.<br /><br />His recent publications include:<br /><br /><em><a href=\"http://www.press.uchicago.edu/ucp/books/book/chicago/E/bo5747718.html\">The End of Sacrifice: Religious Transformations of Late Antiquity</a></em> (Chicago, 2009; paperback 2012)<br /><em><a href=\"http://www.hup.harvard.edu/catalog.php?isbn=9780674048607\">A New Science: the Discovery of Religion in the Age of Reason</a></em> (Cambridge, Mass., 2010)<br /><em><a href=\"https://global.oup.com/academic/product/the-making-of-the-abrahamic-religions-in-late-antiquity-9780198738862?cc=il&lang=en\">The Making of the Abrahamic Religions in Late Antiquity</a></em> (Oxford, 2015)<br />He is the co-editor, with Adam Silverstein, of <em><a href=\"https://global.oup.com/academic/product/the-oxford-handbook-of-the-abrahamic-religions-9780199697762?cc=il&lang=en\">The Oxford Handbook of the Abrahamic Religions</a></em> (Oxford, 2015)."
        links:
            Academia.edu: https://huji.academia.edu/guystroumsa
    jw:
        name: Judith Weingarten
        bio: "Judith Weingarten studied Classical Archaeology at the University of Oxford and is a member of the British School of Athens. She has excavated for many years on Crete and on the Greek mainland and travelled extensively in the Middle East. She has lived and worked among the ruins of the three great Caravan Cities: Petra, Palmyra, and Baalbek. Whilst living within the grounds of the Temple of Bel in Palmyra she began to write her historical novel on [Zenobia, Queen of Palmyra]( http://www.amazon.com/The-Chronicle-Zenobia-Rebel-Queen/dp/1843862190), and the rebellion that she led against imperial Rome."
        links:
            Blog: judithweingarten.blogspot.com
            Academia.edu: https://bsa.academia.edu/judithweingarten
    kt:
        name: Keith Tribe
        bio: "Keith Tribe is economic historian with a long-standing interest in language and translation. Born in London, he now lives on the Herefordshire-Worcestershire border near Malvern. Keith studied at Essex University and Cambridge, and did postdoctoral work in Heidelberg and Göttingen. Between 1976 to 2002 he taught first sociology and then economics at Keele University. His publications include: [_The Economy of the Word_]( https://global.oup.com/academic/product/the-economy-of-the-word-9780190211615?cc=il&lang=en&), Oxford, 2015; [_Strategies of Economic Order: German Economic Discourse, 1750-1950_]( http://www.cambridge.org/il/academic/subjects/economics/history-economic-thought-and-methodology/strategies-economic-order-german-economic-discourse-17501950), Cambridge, 2007, and [_Land, Labour, and Economic Discourse_]( https://books.google.co.il/books/about/Land_labour_and_economic_discourse.html?id=gv25AAAAIAAJ&redir_esc=y), London, 1978."
        links:
            Blog: http://keithtribe.co.uk/
            Academia.edu: https://independent.academia.edu/KeithTribe
    th:
        name: Tom Hillman
        bio: "Born and raised in New York City, Tom for some years had the great pleasure of teaching Latin, Greek, and Ancient History at colleges in the northeastern US. Of late he is parsing his way through Beowulf, and looking forward to Old Norse. He loves baseball, books, and the music of the sea."
        links:
            Blog: http://alasnotme.blogspot.com/
            GooglePlus: https://plus.google.com/107507259485817913355/about
            Twitter: https://twitter.com/alas_not_me
    mm:
        name: Mark McKerracher
        bio: "Mark McKerracher is an independent writer and researcher of agricultural archaeology, specializing in the Anglo-Saxon period."
        links:
            Blog: https://farmingunearthed.wordpress.com/
            Academia.edu: https://independent.academia.edu/MarkMcKerracher

# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/
